# define a dictionary for keeping track of what is where
global column_no_to_name


get_column_name = {0: 'jet pt',
                   1: 'jet eta', 
                   2: 'jet phi',
                   3: 'jet index', 
                   4: 'clus pt 1', 
                   5: 'clus eta 1', 
                   6: 'clus phi 1', 
                   7: 'clus PreSamplerB 1', 
                   8: 'clus EMB1 1', 
                   9: 'clus EMB2 1', 
                   10: 'clus EMB3 1', 
                   11: 'clus PreSamplerE 1', 
                   12: 'clus EME1 1', 
                   13: 'clus EME2 1', 
                   14: 'clus EME3 1', 
                   15: 'clus HEC0 1', 
                   16: 'clus HEC1 1', 
                   17: 'clus HEC2 1', 
                   18: 'clus HEC3 1', 
                   19: 'clus TileBar0 1', 
                   20: 'clus TileBar1 1', 
                   21: 'clus TileBar2 1', 
                   22: 'clus TileGap1 1', 
                   23: 'clus TileGap2 1', 
                   24: 'clus TileGap3 1', 
                   25: 'clus TileExt0 1', 
                   26: 'clus TileExt1 1', 
                   27: 'clus TileExt2 1', 
                   28: 'clus FCAL0 1', 
                   29: 'clus FCAL1 1', 
                   30: 'clus FCAL2 1', 
                   31: 'clus time 1',
                   676: 'track_pt 1',
                   677: 'track_eta 1',
                   678: 'track_phi 1',
                   679: 'track_d0 1',
                   680: 'track_z0 1',
                   681: 'track_PixShared 1',
                   682: 'track_SCTShared 1',
                   683: 'track_PixHoles 1',
                   684: 'track_SCTHoles 1',
                   685: 'track_PixelHits 1',
                   686: 'track_SCTHits 1',
                   896: 'MSeg_etaPos 1',
                   897: 'MSeg_phiPos 1',
                   898: 'MSeg_etaDir 1',
                   899: 'MSeg_phiDir 1',
                   900: 'MSeg_t0 1',
                   1241: 'MSeg_etaPos end',
                   1242: 'MSeg_phiPos end',
                   1243: 'MSeg_etaDir end',
                   1244: 'MSeg_phiDir end',
                   1245: 'MSeg_t0 end'
			}

get_column_no = dict((reversed(item) for item in get_column_name.items()))
